### ISSUE TITLE
`python-isort-buffer` doesn't work with isort `4.3.21`

### ISSUE THREAD

**Issue by twmr** [wyuenho/emacs-python-isort#3]
When I run `python-isort-buffer` in a buffer, the following error is output: 

```
Traceback (most recent call last):
  File "/home/thomashisch/.cache/pre-commit/repol3458474/py_env-python3/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/home/thomashisch/.cache/pre-commit/repol3458474/py_env-python3/lib/python3.9/site-packages/isort/main.py", line 343, in main
    SortImports(file_=file_, write_to_stdout=True, **arguments)
TypeError: isort.isort.SortImports() got multiple values for keyword argument 'write_to_stdout'
```
in  a `*python-isort errors*` buffer.

(note that the default value of `python-isort-arguments` is used)

Currently I can't upgrade to a newer isort version because I have to use this isort version for my projects.

Do you know how I can debug this? I wanted to reproduce this error on the command line by running 

`cat myfile | /home/thomashisch/.cache/pre-commit/repol3458474/py_env-python3/bin/isort --stdout --atomic -`

but this worked. 

Note that I don't have problems when I use `python-isort-on-save-mode`, but my `--settings-path` is not taken into account (I have included this path in `python-isort-arguements, but it is ignored)

**Comment by twmr** [comment]
I managed to fix this problem by removing the `--stdout` flag from the list of `python-isort-arguemnts`.
